from Instruction import Instruction

__author__ = 'def'

class StartInstruction(Instruction):
    def __init__(self):
        self.code = ";Code generated by LightPainter\n"
        self.code +="M42 P6 S0 ;turn off led\n"
        self.code +="M42 P5 S0 ;turn off led\n"
        self.code +="M42 P4 S0 ;turn off led\n"
        self.code +="G21        ;metric values\n"
        self.code +="G90        ;absolute positioning\n"
        self.code +="M107       ;start with the fan off\n"
        self.code +="G28 Y0     ;move Y to min endstops\n"
        self.code +="G28 X0     ;move X to min endstops\n"

    def generate_code(self):
        return self.code